language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: true

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - curl -L -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.3.3/elasticsearch-2.3.3.tar.gz
  - tar -xvf elasticsearch-2.3.3.tar.gz

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require fxp/composer-asset-plugin:~1.0
  - travis_retry composer install --prefer-dist --no-interaction --dev

before_script:
  - mysql -e 'create database yii2_datastructure;'

script:
  - elasticsearch-2.3.3/bin/elasticsearch &
  - sleep 10
  - vendor/bin/phpunit --coverage-clover=coverage.xml --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      pwd
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

cache:
  - vendor
  - $HOME/.composer/cache

after_success:
  - |
    if [ $TRAVIS_PHP_VERSION = '5.6' ]; then
      bash <(curl -s https://codecov.io/bash)
    fi
